### ISSUE TITLE
How can i detect editorjs has change in custom plugin 

### ISSUE THREAD

**Issue by fxcjahid** [editor-js/create-tool#3]
Hello,
I am start building custom plugin for editorjs. 
I need to detect text `( H1...H6 )` has changed in editor..
Mainly, The plugin developed for **Table of content** so it must be need to detect on change. 

I found that code:
`new Editor({
    ...otherProps,
    onChange: handleOnChange 
}) `

But, it only working on editojs but not work in custom plugin

**Comment by talyguryn** [comment]
Issue is not referred to this repository. Please ask it in [codex-team/editor.js](https://github.com/codex-team/editor.js).
